vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: '%app.path.images%/avatar'
            upload_destination: '%kernel.root_dir%/../public/uploads/images/avatar'
