parameters:
    locale: 'en'
    app.path.images: '/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    kernel.listener.doctrine:
        class: 'App\Listener\DoctrineListener'
        public: false
        tags:
            - { name: doctrine.event_listener, event: preFlush, method: preFlush }

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]